//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLTA.Common.Core.DataAccess {
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    
    
    public class EntityIdSet : INullable, IOracleCustomType, IXmlSerializable {

		public const string ENTITY_ID_SET = "ENTITY_ID_SET";

		private bool m_IsNull;

		private EntityId[] m_ENTITY_ID;
        
        public EntityIdSet() {
            // TODO : Add code to initialise the object
        }
        
        public EntityIdSet(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        
        public static EntityIdSet Null {
            get {
                EntityIdSet obj = new EntityIdSet();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleArrayMappingAttribute()]
		public virtual EntityId[] Value
		{
            get {
                return this.m_ENTITY_ID;
            }
            set {
                this.m_ENTITY_ID = value;
	            m_IsNull = false;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            OracleUdt.SetValue(con, pUdt, 0, this.m_ENTITY_ID);
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
			this.m_ENTITY_ID = ((EntityId[])(OracleUdt.GetValue(con, pUdt, 0)));
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static EntityIdSet Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new EntityIdSet();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("ENTITY_ID_SET")]
    public class EntityIdSetFactory : IOracleCustomTypeFactory, IOracleArrayTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            EntityIdSet obj = new EntityIdSet();
            return obj;
        }
        
        public virtual System.Array CreateArray(int length) {
			EntityId[] collElem = new EntityId[length];
            return collElem;
        }
        
        public virtual System.Array CreateStatusArray(int length) {
            return null;
        }
    }
}
