//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLTA.Common.Core.DataAccess {
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    
    
    public class EntityId : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        
        private decimal m_ID;
        
        private bool m_IDIsNull;
        
        public EntityId() {
            // TODO : Add code to initialise the object
            this.m_IDIsNull = true;
        }
        
        public EntityId(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        
        public static EntityId Null {
            get {
                EntityId obj = new EntityId();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleObjectMappingAttribute("ID_VALUE")]
        public decimal ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
	            IDIsNull = false;
            }
        }
        
        public bool IDIsNull {
            get {
                return this.m_IDIsNull;
            }
            set {
                this.m_IDIsNull = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            if ((IDIsNull == false)) {
                Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ID_VALUE", this.ID);
            }
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.IDIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "ID_VALUE");
            if ((IDIsNull == false)) {
                this.ID = ((decimal)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ID_VALUE")));
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static EntityId Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new EntityId();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("ENTITY_ID")]
    public class EntityIdFactory : IOracleCustomTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            EntityId obj = new EntityId();
            return obj;
        }
    }
}
